### ISSUE TITLE
Ticking block entity (net/minecraft/client/resources/I18n)

### ISSUE THREAD

**Issue by Krutoy242** [tgstyle/MCT-Smeltery-IO#2]
After updating mod from `1.12.2-1.2.53` to `1.12.2-1.2.54` loading old world on server causing `Ticking block entity` crash:

[Server-crush.txt](https://gist.github.com/Krutoy242/8f370c8d653ae04809f13144d538c615)

Downgrading back to 53 works fine.
I would give addition information if needed.

**Comment by tgstyle** [comment]
https://github.com/tgstyle/MCT-Smeltery-IO/commit/839fe891e15cc655745eddd5ed0d010e95efcfa8
