### ISSUE TITLE
problem with smeltery casting machine

### ISSUE THREAD

**Issue by Mogat** [tgstyle/MCT-Smeltery-IO#3]
Version 1.2.55

I am playing the modpack Awakening - Sky of Diamonds.

The problem I am having is that the casting machine can put the ice balls in every slot of the machine. Making almost impossible to automate. I have tried to use several types of hoppers, wireless gps, and item conduits all with the same results. Otherwise loving the mod!

**Comment by tgstyle** [comment]
https://github.com/tgstyle/MCT-Smeltery-IO/commit/f9589a59b1046a80baad49a7832a92a9992c684c
