### ISSUE TITLE
[Suggestion] Configurable maxStackSize for Ice Balls

### ISSUE THREAD

**Issue by Krutoy242** [tgstyle/MCT-Smeltery-IO#4]
Right now its `16`. It would be nice to set it up to `64`.

I making huge modpack with a lot of automatization. There is arrays of **Casting Machines**, and they consuming stacks per second or even tick. I would like to be able enlarge stack size for Ice Balls to help players with automatization.

Before, I used CraftTweaker setter to change max stack size, but its not working somehow
```zs
<mctsmelteryio:iceball>.maxStackSize = 64;
```

**Comment by tgstyle** [comment]
This will be in the next release.
